### ISSUE TITLE
Split out the dependencies parsing and merging from go()

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#149]
Just an attempt to cleanup a little that too-big main function.

Of course, what is put everywhere else, should be tested :)

**Comment by andresdelfino** [comment]
HI, I'm working on this one, but my branch just adds a _get_deps to put that logic out of go(), but I saw that the _merge_deps already existed at the time this issue was opened, and the title ("Split out the dependencies parsing *and merging* from go()") got me confused when I read it a second time.

This is my branch: https://github.com/PyAr/fades/compare/master...andresdelfino:put-go-on-diet?expand=1

I have to work on the the test cases yet.

Could you confirm if I got the idea of the issue or if there's something I'm missing?

**Comment by facundobatista** [comment]
Yes, that's the general idea.

However, I'd rename the new function, maybe called `consolidate_dependencies`, as you're not "getting" them from anywhere (mostly), just grouping them, but your choice.

And please improve the function argument names, more on the "what means for this function" meanings.. like `needs_ipython`, `child_program`, `requirement_files`, `manual_dependencies` (this last one mainly because "dependencies" was too generic).

The `executable` parameter it's another thing. Why do we need it? Can't we just decide for the case where `child_program` is not there? (`None` or `""`?). This is one of the things you need to improve in this branch.

Finally: probably the small `_merge_deps` can be just inside (inline) this new function...

Thanks!!!

**Comment by andresdelfino** [comment]
I updated the branch with all changes applied, except the one regarding executable parameter.

I believe there's no problem if no child is specified, but if one **is** specified, we need to know if the child program is provided by the venv or not in order to parse it or not. Does this make any sense?

**Comment by andresdelfino** [comment]
After a quick Telegram chat we got this things solved. I updated the branch accordingly. I was thinking about making the PR when I have the tests ready; if you think otherwise, please tell me so.

**Comment by facundobatista** [comment]
Looks solid. Time for testing! 

Thanks!!!

**Comment by andresdelfino** [comment]
Four things regarding the PR:

1. I changed the way child programs are dealt with in consolidate_dependencies. Instead of asking for a _is_child_from_venv parameter, we just let the caller have this logic. If no child program is specified, or if it is installed in the venv, the caller must pass None, or nothing at all, see below.

2. I added defaults for all parameters. They allow simpler calls in the test suite, and might be useful for someone using the function.

2. You'll note that as we are now working with actual dependencies at the merging stage, we now have to use "real" dependencies to try it out, and, also, "real" consolidated dependencies are being returned. That's why we now have to use Requirement.parse and parsing.VCSDependency.

3. As to replicate the different dependencies "origins" that the old tests had (d1, d2, d3), I used all the available options to have different origins as well, which leads to several new test files. But, since at that stage what we are actually testing is just the merging, perhaps we can just test everything using manual dependencies?

**Comment by facundobatista** [comment]
Awesome, thanks!

Some general details, before doing a proper review, responses to your points...

But first, note that your branch DOES have conflicts. Maybe you don't have an updated "master" in your fork?

So...

1. it may be ok, but I'm not sure I'm looking everything correctly, because of the conflicts. In any case don't do the `args.child_program if not args.executable else None` inside the function call, do it before and store that in a variable with a sensible name like `external_child_program` or similar, and it will be much clearer.

2. Don't add defaults for all parameters. Production code should not have stuff only for the tests, it makes it much difficult to understand later. Think in somebody trying to comprehend the code, seeing that the parameter is optional, then searching in which cases nothing is passed, etc. It may be useful for somebody in the future, yes, but don't add code for future needs, more code is always more bugs, so don't add code just because.

3. Ok

4. I don't like the new test files. IMO, test files should be included in the project tests for real examples from external parties (an .html, a json response, etc), or our own data if it's complex and cumbersome to include in the test modules themselves. But in this case, the test files are very small and easy to generate dynamically during the tests... I'm thinking a helper function like `self.generate_test_file("2", "2") which will create a temp file with those lines, add a cleanup to remove the file, and then return the file name for the test

Thanks!!!

**Comment by andresdelfino** [comment]
You were right, my fork wasn't up to date with upstream/master :sweat_smile: 

Hopefully, I have addressed all your comments. I did made a small change to your generate_test_file function idea though: it takes an iterable instead of multiple parameters. Felt better to me.
